<a href="https://www.kaggle.com/code/averma111/pytorch-pss3e18-vanilla?scriptVersionId=135302069" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [16]:

import random
import numpy as np 
import pandas as pd 
import os
import datetime
import seaborn as sns
from tqdm.notebook import tqdm

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader,TensorDataset,random_split,SubsetRandomSampler, ConcatDataset
from torch.nn import functional as F



import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')
import itertools

In [17]:
for dirname, _, filenames in os.walk('/kaggle/input/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/playground-series-s3e18/sample_submission.csv
/kaggle/input/playground-series-s3e18/train.csv
/kaggle/input/playground-series-s3e18/test.csv


In [18]:
class Datapreparation(object):
    
    def __init__(self,root_path):
        self.root_path = root_path
        
    def get_dataframe(self,filename):
        return pd.read_csv(os.path.join(self.root_path,filename))
    
    def summary(self,text, df):
        summary = pd.DataFrame(df.dtypes, columns=['dtypes'])
        summary['null'] = df.isnull().sum()
        summary['unique'] = df.nunique()
        summary['min'] = df.min()
        summary['median'] = df.median()
        summary['max'] = df.max()
        summary['mean'] = df.mean()
        summary['std'] = df.std()
        summary['duplicate'] = df.duplicated().sum()
        return summary
    
    
    def random_split_data(self,X,y):
        return train_test_split(X, y,test_size=0.20,random_state=42)

 
    def standardization_data(self,X_data):
        scaler = StandardScaler()
        std_X_data = scaler.fit_transform(X_data)
        return std_X_data
    

    
data = Datapreparation('/kaggle/input/playground-series-s3e18')
train=data.get_dataframe('train.csv')

In [19]:
data.summary('train',train)

dtypes  null  unique         min       median  \
id                   int64     0   14838    0.000000  7418.500000   
BertzCT            float64     0    2368    0.000000   290.987941   
Chi1               float64     0    1259    0.000000     6.485270   
Chi1n              float64     0    3157    0.000000     4.052701   
Chi1v              float64     0    3306    0.000000     4.392859   
Chi2n              float64     0    3634    0.000000     2.970427   
Chi2v              float64     0    3725    0.000000     3.242775   
Chi3v              float64     0    3448    0.000000     1.948613   
Chi4n              float64     0    2930    0.000000     1.073261   
EState_VSA1        float64     0     719    0.000000    17.353601   
EState_VSA2        float64     0     445    0.000000     6.420822   
ExactMolWt         float64     0    1666    1.007276   206.042653   
FpDensityMorgan1   float64     0     556 -666.000000     1.250000   
FpDensityMorgan2   float64     0     650 -666.000000     1.865152   
FpDensityMorgan3   float64     0     654 -666.000000     2.358491   
HallKierAlpha      float64     0     388   -7.730000    -1.100000   
HeavyAtomMolWt     float64     0     860    0.000000   194.276500   
Kappa3             float64     0    2245 -104.040000     3.261011   
MaxAbsEStateIndex  float64     0    2356    0.000000    10.421334   
MinEStateIndex     float64     0    2142   -6.327514    -1.265370   
NumHeteroatoms       int64     0      40    0.000000     6.000000   
PEOE_VSA10         float64     0     250    0.000000     6.041841   
PEOE_VSA14         float64     0     291    0.000000     5.969305   
PEOE_VSA6          float64     0     219    0.000000     0.000000   
PEOE_VSA7          float64     0     262    0.000000     0.000000   
PEOE_VSA8          float64     0     237    0.000000     0.000000   
SMR_VSA10          float64     0     409    0.000000    11.752550   
SMR_VSA5           float64     0     492    0.000000    20.075376   
SlogP_VSA3         float64     0     217    0.000000     9.589074   
VSA_EState9        float64     0    1946   -5.430556    41.666667   
fr_COO               int64     0       8    0.000000     0.000000   
fr_COO2              int64     0       8    0.000000     0.000000   
EC1                  int64     0       2    0.000000     1.000000   
EC2                  int64     0       2    0.000000     1.000000   
EC3                  int64     0       2    0.000000     0.000000   
EC4                  int64     0       2    0.000000     0.000000   
EC5                  int64     0       2    0.000000     0.000000   
EC6                  int64     0       2    0.000000     0.000000   

                            max         mean          std  duplicate  
id                 14837.000000  7418.500000  4283.505982          0  
BertzCT             4069.959780   515.153604   542.456370          0  
Chi1                  69.551167     9.135189     6.819989          0  
Chi1n                 50.174588     5.854307     4.647064          0  
Chi1v                 53.431954     6.738497     5.866444          0  
Chi2n                 32.195368     4.432570     3.760516          0  
Chi2v                 34.579313     5.253221     4.925065          0  
Chi3v                 22.880836     3.418749     3.436208          0  
Chi4n                 16.072810     1.773472     1.865898          0  
EState_VSA1          363.705954    29.202823    31.728679          0  
EState_VSA2           99.936429    10.435316    13.651843          0  
ExactMolWt          2237.318490   292.623087   225.384140          0  
FpDensityMorgan1       3.000000     1.236774     5.491284          0  
FpDensityMorgan2       3.200000     1.812070     5.495565          0  
FpDensityMorgan3       3.400000     2.255470     5.501200          0  
HallKierAlpha          0.820000    -1.207776     0.935314          0  
HeavyAtomMolWt      2035.133000   274.950211   212.678755          0  
Kappa3              1512.242231     5.874372    45

In [20]:
y1 = train['EC1']
y2 = train['EC2']
train.drop(columns=['id','EC1','EC2','EC3','EC4','EC5','EC6'],axis=1,inplace=True)
X = train.copy()

In [22]:
X_train,X_val,y1_train,y1_val = data.random_split_data(X,y1)
print(X_train.shape,X_val.shape,y1_train.shape,y1_val.shape)

(11870, 31) (2968, 31) (11870,) (2968,)


In [23]:
X_train,X_val,y2_train,y2_val = data.random_split_data(X,y2)
print(X_train.shape,X_val.shape,y2_train.shape,y2_val.shape)

(11870, 31) (2968, 31) (11870,) (2968,)


In [24]:
std_X_train = data.standardization_data(X_train)
std_X_val = data.standardization_data(X_val)
print(std_X_train[0],std_X_val[0])

[-0.6460012  -0.49660398 -0.53250602 -0.57261284 -0.5904852  -0.61753263
 -0.59673579 -0.62771573 -0.91411097  0.56344636 -0.56889535 -0.07305243
  0.81469479  1.50215144  0.0217275  -0.57591696 -0.08736038 -0.39329628
  1.34611003 -0.72802128 -0.78622974 -0.51646882  0.1563295   0.31295018
 -0.61487415 -0.5171512  -0.91283104 -0.93428166 -0.94969081 -0.68328343
 -0.68460195] [-0.73157789 -0.89416128 -0.71611727 -0.71782103 -0.74457679 -0.73521665
 -0.8362178  -0.84437652 -0.385045   -0.76779355 -0.74586676  0.06227215
  0.02884275  0.07397899  0.41849986 -0.75437549 -0.10510849 -0.80384358
  0.35858918 -0.61099998 -0.3717161  -0.33573224 -0.47165217 -0.56987761
 -0.62586121 -0.22583258 -0.54067893 -0.28699515 -0.54836477  0.78492852
  0.78337988]


In [25]:
class Tensoroperations():
    
    def __init__(self):
        super(Tensoroperations,self).__init__()
    
    def convert_to_tensor(self,X,y=None):
        X_tensor =  torch.from_numpy(X).float()   
        y_tensor = torch.from_numpy(y).float() 
        return X_tensor,y_tensor
        
    def convert_to_test_tesnor(self,X):
        X_tensor =  torch.from_numpy(X).float()
        return X_tensor
    
    def get_dataloaders(self,train_dataset,val_dataset):
        train_loaders = DataLoader(train_dataset,batch_size=32,shuffle=True)
        val_loaders = DataLoader(val_dataset,batch_size=32)
        return train_loaders,val_loaders
    
    def get_test_dataloaders(self,test_dataset,X_test):
        test_loaders = DataLoader(test_dataset,batch_size=X_test.shape[0])
        return test_loaders
        
        
    
tenops = Tensoroperations()

In [26]:
class CustomDataset(Dataset):
    
    def __init__(self,X_data,y_data=None,is_train=True):
        super().__init__()
        if is_train:
            self.X_data = X_data
            self.y_data = y_data
        else:
            self.X_data=X_train
            
    def __getitem__(self,index):
        return (self.X_data[index],self.y_data[index])
    
    def __len__(self):
        return len(self.X_data)

In [27]:
X_tensor_train,y1_tensor_train = tenops.convert_to_tensor(std_X_train,y1_train.values)
X_tensor_val,y1_tensor_val = tenops.convert_to_tensor(std_X_val,y1_val.values)
print('The training tensor for EC1\n',X_tensor_train,y1_tensor_train)
print('The validation tensor for EC1\n',X_tensor_val,y1_tensor_val)

The training tensor for EC1
 tensor([[-0.6460, -0.4966, -0.5325,  ..., -0.9497, -0.6833, -0.6846],
        [-0.7818, -0.9513, -0.8922,  ..., -1.0127,  0.8178,  0.8161],
        [ 2.1245,  1.5223,  1.7448,  ...,  2.0297, -0.6833, -0.6846],
        ...,
        [-0.2776,  0.0232, -0.3406,  ..., -0.6133, -0.6833, -0.6846],
        [-0.7166, -0.6467, -0.5530,  ..., -0.6577, -0.6833, -0.6846],
        [-0.8225, -0.8068, -0.8795,  ..., -0.8180, -0.6833, -0.6846]]) tensor([1., 1., 1.,  ..., 0., 0., 1.])
The validation tensor for EC1
 tensor([[-0.7316, -0.8942, -0.7161,  ..., -0.5484,  0.7849,  0.7834],
        [-0.2605,  0.2136,  0.2536,  ..., -0.2027, -0.6970, -0.6985],
        [-0.4432, -1.0872, -1.1129,  ..., -0.1914,  2.2669,  2.2653],
        ...,
        [-0.6615, -0.6798, -0.6762,  ..., -0.3160,  0.7849,  0.7834],
        [ 0.7218,  0.9378,  0.8351,  ...,  0.2456, -0.6970, -0.6985],
        [-0.8259, -0.8942, -0.8957,  ..., -0.9963, -0.6970, -0.6985]]) tensor([1., 0., 1.,  ..., 1., 0.,

In [29]:
X_tensor_train,y2_tensor_train = tenops.convert_to_tensor(std_X_train,y2_train.values)
X_tensor_val,y2_tensor_val = tenops.convert_to_tensor(std_X_val,y2_val.values)
print('The training tensor EC2\n',X_tensor_train,y2_tensor_train)
print('The validation tensor Ec2\n',X_tensor_val,y2_tensor_val)

The training tensor EC2
 tensor([[-0.6460, -0.4966, -0.5325,  ..., -0.9497, -0.6833, -0.6846],
        [-0.7818, -0.9513, -0.8922,  ..., -1.0127,  0.8178,  0.8161],
        [ 2.1245,  1.5223,  1.7448,  ...,  2.0297, -0.6833, -0.6846],
        ...,
        [-0.2776,  0.0232, -0.3406,  ..., -0.6133, -0.6833, -0.6846],
        [-0.7166, -0.6467, -0.5530,  ..., -0.6577, -0.6833, -0.6846],
        [-0.8225, -0.8068, -0.8795,  ..., -0.8180, -0.6833, -0.6846]]) tensor([1., 1., 0.,  ..., 1., 1., 1.])
The validation tensor Ec2
 tensor([[-0.7316, -0.8942, -0.7161,  ..., -0.5484,  0.7849,  0.7834],
        [-0.2605,  0.2136,  0.2536,  ..., -0.2027, -0.6970, -0.6985],
        [-0.4432, -1.0872, -1.1129,  ..., -0.1914,  2.2669,  2.2653],
        ...,
        [-0.6615, -0.6798, -0.6762,  ..., -0.3160,  0.7849,  0.7834],
        [ 0.7218,  0.9378,  0.8351,  ...,  0.2456, -0.6970, -0.6985],
        [-0.8259, -0.8942, -0.8957,  ..., -0.9963, -0.6970, -0.6985]]) tensor([1., 1., 1.,  ..., 1., 1., 1.])


In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.manual_seed(42)
criterion = nn.CrossEntropyLoss()
     

In [ ]:
dataset = ConcatDataset([train_dataset, test_dataset])

num_epochs=10
batch_size=128
k=10
splits=KFold(n_splits=k,shuffle=True,random_state=42)
foldperf={}

In [ ]:
def train_epoch(model,device,dataloader,loss_fn,optimizer):
    train_loss,train_correct=0.0,0
    model.train()
    for images, labels in dataloader:

        images,labels = images.to(device),labels.to(device)
        optimizer.zero_grad()
        output = model(images)
        loss = loss_fn(output,labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * images.size(0)
        scores, predictions = torch.max(output.data, 1)
        train_correct += (predictions == labels).sum().item()

    return train_loss,train_correct

In [ ]:
def valid_epoch(model,device,dataloader,loss_fn):
    valid_loss, val_correct = 0.0, 0
    model.eval()
    with torch.no_grad():
      for images, labels in dataloader:

          images,labels = images.to(device),labels.to(device)
          output = model(images)
          loss=loss_fn(output,labels)
          valid_loss+=loss.item()*images.size(0)
          scores, predictions = torch.max(output.data,1)
          val_correct+=(predictions == labels).sum().item()

    return valid_loss,val_correct

In [ ]:
history = {'train_loss': [], 'test_loss': [],'train_acc':[],'test_acc':[]}

for fold, (train_idx,val_idx) in enumerate(splits.split(np.arange(len(dataset)))):

    print('Fold {}'.format(fold + 1))

    train_sampler = SubsetRandomSampler(train_idx)
    test_sampler = SubsetRandomSampler(val_idx)
    train_loader = DataLoader(dataset, batch_size=batch_size, sampler=train_sampler)
    test_loader = DataLoader(dataset, batch_size=batch_size, sampler=test_sampler)
    
    model = ConvNet()
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.002)

    for epoch in range(num_epochs):
        train_loss, train_correct=train_epoch(model,device,train_loader,criterion,optimizer)
        test_loss, test_correct=valid_epoch(model,device,test_loader,criterion)

        train_loss = train_loss / len(train_loader.sampler)
        train_acc = train_correct / len(train_loader.sampler) * 100
        test_loss = test_loss / len(test_loader.sampler)
        test_acc = test_correct / len(test_loader.sampler) * 100

        print("Epoch:{}/{} AVG Training Loss:{:.3f} AVG Test Loss:{:.3f} AVG Training Acc {:.2f} % AVG Test Acc {:.2f} %".format(epoch + 1,
                                                                                                             num_epochs,
                                                                                                             train_loss,
                                                                                                             test_loss,
                                                                                                             train_acc,
                                                                                                             test_acc))
        history['train_loss'].append(train_loss)
        history['test_loss'].append(test_loss)
        history['train_acc'].append(train_acc)
        history['test_acc'].append(test_acc)  

In [ ]:
avg_train_loss = np.mean(history['train_loss'])
avg_test_loss = np.mean(history['test_loss'])
avg_train_acc = np.mean(history['train_acc'])
avg_test_acc = np.mean(history['test_acc'])

print('Performance of {} fold cross validation'.format(k))
print("Average Training Loss: {:.4f} \t Average Test Loss: {:.4f} \t Average Training Acc: {:.3f} \t Average Test Acc: {:.3f}".format(avg_train_loss,avg_test_loss,avg_train_acc,avg_test_acc))  


In [ ]:
testl_f,tl_f,testa_f,ta_f=[],[],[],[]
k=10
for f in range(1,k+1):

     tl_f.append(np.mean(foldperf['fold{}'.format(f)]['train_loss']))
     testl_f.append(np.mean(foldperf['fold{}'.format(f)]['test_loss']))

     ta_f.append(np.mean(foldperf['fold{}'.format(f)]['train_acc']))
     testa_f.append(np.mean(foldperf['fold{}'.format(f)]['test_acc']))

print('Performance of {} fold cross validation'.format(k))
print("Average Training Loss: {:.3f} \t Average Test Loss: {:.3f} \t Average Training Acc: {:.2f} \t Average Test Acc: {:.2f}".f

In [ ]:
diz_ep = {'train_loss_ep':[],'test_loss_ep':[],'train_acc_ep':[],'test_acc_ep':[]}

for i in range(num_epochs):
      diz_ep['train_loss_ep'].append(np.mean([foldperf['fold{}'.format(f+1)]['train_loss'][i] for f in range(k)]))
      diz_ep['test_loss_ep'].append(np.mean([foldperf['fold{}'.format(f+1)]['test_loss'][i] for f in range(k)]))
      diz_ep['train_acc_ep'].append(np.mean([foldperf['fold{}'.format(f+1)]['train_acc'][i] for f in range(k)]))
      diz_ep['test_acc_ep'].append(np.mean([foldperf['fold{}'.format(f+1)]['test_acc'][i] for f in range(k)]))

In [ ]:
# Plot losses
plt.figure(figsize=(10,8))
plt.semilogy(diz_ep['train_loss_ep'], label='Train')
plt.semilogy(diz_ep['test_loss_ep'], label='Test')
plt.xlabel('Epoch')
plt.ylabel('Loss')
#plt.grid()
plt.legend()
plt.title('CNN loss')
plt.show()
     

In [ ]:

# Plot accuracies
plt.figure(figsize=(10,8))
plt.semilogy(diz_ep['train_acc_ep'], label='Train')
plt.semilogy(diz_ep['test_acc_ep'], label='Test')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
#plt.grid()
plt.legend()
plt.title('CNN accuracy')
plt.show()